### ISSUE TITLE
Build failes

### ISSUE THREAD

**Issue by jcaldwell** [reactor/reactor-quickstart#10]
./gradelw compileJava fails.

Could not find io.projectreactor.spring:reactor-spring-context:1.1.0.RC1

https://drone.io/github.com/reactor/reactor-quickstart/28

**Comment by jbrisbin** [comment]
Looks like the quickstart app needs to be updated to Reactor's 2.0 API.

**Comment by jbrisbin** [comment]
Should now be fixed in b087d19ad54e0b8353608dbd5829fa35d840547b
